server:
  port: 9000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: cloud-gateway
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 114.116.83.151
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      default-filters:
      routes:
        - id: cloud-authen
          uri: lb://cloud-authen
          predicates:
            - Path=/authen/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    com.microservice.cloud.gateway: info
    org.springframework.cloud.gateway: debug
