server:
  port: 8761
spring:
  application:
    name: cloud-eureka
  output:
    ansi:
      enabled: detect
  rabbitmq:
    host: 114.116.83.151
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    register-with-eureka: false   #是否将自己注册到Eureka服务
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    prefer-ip-address: true #将自己的ip注册到eureka中
  server:
    enable-self-preservation: true #是否开启自我保护
    eviction-interval-timer-in-ms: 60000 #清理间隔
management:
  endpoints:
    web:
      exposure:
        include: "*"
